### ISSUE TITLE
Error 403: Forbidden | Default Code and Configuration

### ISSUE THREAD

**Issue by Exius999** [parafoxia/analytix#41]
Hello,

I am facing an issue with "Error 403: Forbidden" with the default code from this projects home page.

Perhaps there is a chance I have messed up somewhere in the Google Developer Cloud, however I was successfully able to create both the secrets.json and tokens.json and ensure that the file paths are correctly set.

I enabled the "YouTube Analytics API" and set the scope for it for the last 2 options on the scope list as instructed in the YouTube video [here](https://www.youtube.com/watch?v=opFHHhuI_5A).

It's set to use external with testing enabled and my email address was added to the test list which was the same email I authorized in the OAuth stage when I ran the application for the first time. Now when I attempt to run it again with the added tokens.json now in my project directory, the code throws "Error: 403". The OAuth Client ID is also currently set to Desktop.

Unlike the video however, I have updated the initialization code to reflect what's on this project page and I have enabled logging as you can see in the screenshot I have provided.

<img width="853" alt="Error" src="https://user-images.githubusercontent.com/45151674/196370438-f33bf87e-7eab-4a29-977b-7f2a903bb58f.png">

**Comment by parafoxia** [comment]
A few things to try:

1. Make sure your channel is owned by the Google account you've provided as a test email.
2. Make sure the test email was actually added -- sometimes it just doesn't set correctly.
3. Try calling `client.refresh_tokens` before the retrieve call and see if that changes anything. I don't expect this to help as analytix should do this automatically, but worth a shot.

If none of those work, I'm not sure what's happening. I have encountered this issue before, but as far as I can tell it seems to only happen with some email addresses. For example, one of my emails does work, one doesn't.

**Comment by parafoxia** [comment]
So I've been experimenting to see if I could replicate the error the used to get, but I have been unsuccessful. I'm not entirely sure what's happening here to be honest.

> Now when I attempt to run it again with the added tokens.json now in my project directory, the code throws "Error: 403".

I'm curious about this bit. Did it successfully work the first time, but not the second? If you remove the `tokens.json` file and try again, does it work?

**Comment by Exius999** [comment]
Yes, after I configured the google developer cloud settings, I added the code seen in the screenshot to my IDE (which is PyCharm as you probably can tell) and ran it. It was able to give me the OAuth link in the console which I clicked that then lead me to a localhost URL screen which I accepted all agreements for that then generated the tokens.json file at the root directory of my PyCharm project.

Everything in your first post has been tested to have not fixed the issue. However, in regards to your last post and having me test removing the tokens.json, I went ahead and did that and re-ran which resulted in the console throwing the OAuth consent screen again.

I clicked authorize using the same test email which is a gmail address and that was the same one I used to configure everything with and re-generated the tokens.json. Once it generated the tokens.json file it then provided error 403 again.

Here are screenshots for your reference.

<img width="733" alt="Screenshot 3" src="https://user-images.githubusercontent.com/45151674/196594718-1b11fb5d-f126-4790-ac7b-744283d85569.png">
<img width="424" alt="Screenshot 2" src="https://user-images.githubusercontent.com/45151674/196594721-b6eb5802-1980-4372-a04d-e853285a7874.png">
<img width="1904" alt="Screenshot 1" src="https://user-images.githubusercontent.com/45151674/196594723-6353e433-e6ad-4299-8bb9-446e01fa2104.png">

**Comment by Exius999** [comment]
I'm not sure if it's just the authentication, but it looks like it's processing data somehow.

<img width="812" alt="Screenshot 5" src="https://user-images.githubusercontent.com/45151674/196596315-b70326e2-5ddc-4356-9121-f83fdd89e455.png">

**Comment by Exius999** [comment]
Looks like I missed the step of checking the stack overflow article, I see it's talking about brand accounts which this is one of.

I'm currently checking what I can do with getting it to resolve for that.

**Comment by parafoxia** [comment]
I'm pretty sure that's confirmed, at least to me, that the issue isn't what I thought it might be. The Stack Overflow answer didn't seem to change anything, so I would remove that new `tokens.json` and revert back to the secrets file you were initially using.

Can you confirm your flow looks something like this:

1. Choose an account (if you only have one account, this might not appear)
2. Choose your account or a brand account — this should a list populated with your email address, and any YouTube channels connected to that account (as shown in the screenshot)
3. Here, when I choose "Carberra Tutorials" (a brand account), it works fine, though when I choose my email address, I get a 500 Internal Server Error. On the email I mentioned before where it didn't used to work, it now works the same way.

![image](https://user-images.githubusercontent.com/43846948/196681914-ae483faa-0c42-48fb-9485-a68e824a8c0a.png)

Any channel I select out of that list works fine, besides just selecting the email address. Are you sure you're selecting a *channel* rather than the email itself? From the screenshot it seems like you're selecting the email instead. It may just be giving you a 403 instead of a 500 in your case for whatever reason.

I tried to look up an error reference for the Analytics API but it doesn't appear to have one. [The Data API does](https://developers.google.com/youtube/v3/docs/errors), but I'm not sure how helpful that would actually be.

The issue is that the Analytics API returns such uninformative errors. analytix does print errors when debug logging is enabled, like so:
```
02255 [  DEBUG  ] analytix.analytics: Data retrieved: {'error': {'code': 500, 'message': 'An internal error has occurred.', 'errors': [{'message': 'An internal error has occurred.', 'domain': 'global', 'reason': 'internalError'}]}}
```

It may be worth using `analytix.setup_logging(logging.DEBUG)` (making sure `logging` is imported), and seeing what it says. Forbidden errors may be a bit more helpful.

**Comment by Exius999** [comment]
I've gone ahead and added the logging.DEBUG which seems to provide more information as you had said.

I was under the impression that the main account I use was listed as a brand account, but I guess that's not the case if the email address is listed with it?

Went ahead and deleted the tokens.json and added the original secrets.json.

<img width="583" alt="Screenshot 2022-10-19 213114" src="https://user-images.githubusercontent.com/45151674/196835935-fe183934-efc5-4158-8289-7c257196ae15.png">

<img width="434" alt="Screenshot 2022-10-19 213143" src="https://user-images.githubusercontent.com/45151674/196835985-6b7d8931-4660-4f88-bc72-2fe802b2c812.png">

<img width="1844" alt="Screenshot 2022-10-19 213600" src="https://user-images.githubusercontent.com/45151674/196835996-ea7d50e7-9292-400c-a7a5-aea83ee669de.png">

<img width="790" alt="Screenshot 2022-10-19 213619" src="https://user-images.githubusercontent.com/45151674/196836008-fe3effd0-b3b5-42ca-b4ef-3ea347df72e4.png">

**Comment by parafoxia** [comment]
On the first screen, you're selecting the Google account. On the second screen, you select either the Google account itself or a brand account connected to the Google account you selected on the first screen.

So in your case, you select your animewulf account, then you have your Exius - Hearthstone, Exius, and KnightWulf brand accounts (which are your YouTube channels).

I think you're selecting your animewulf account, which generates tokens for content owner reports, which analytix doesn't support. You need to select the actual channel you want do retrieve reports for (such as Exius).

Hopefully if you do that you'll get some tokens back. I can't say I've ever seen that malformed code error outside of messing around with the API, but I believe you should be able to ignore that error.

**Comment by Exius999** [comment]
I just selected Exius on the second screen, which generated the tokens.json and then started throwing error 403 again.

**Comment by parafoxia** [comment]
Hm... The only other thing I can think of is the redirect URI. Did you change that within the secrets file directly? If so, that's almost definitely what's causing the problems (even though it appears to be "working" as is).

Try changing the URI to `http://localhost`, within the file.

**Comment by Exius999** [comment]
This is the current secrets file that was generated when I downloaded it. Looks like the redirect URI is already that one.
<img width="936" alt="Screenshot 2022-10-21 222133" src="https://user-images.githubusercontent.com/45151674/197314887-b84645a2-4ab9-4844-9d8e-a0ebb0be3cec.png">

**Comment by parafoxia** [comment]
Huh, that's...weird. Are you running analytix on a server with a domain?

I'm kinda lost if that's not the problem honestly. If you like, you can email me your secrets and tokens and I can see if they're getting malformed somehow. Obviously if you don't feel comfortable doing that that's fine, but there may be something up with them.

**Comment by Exius999** [comment]
Sure, I think that's fine at this point. You've provided a lot of help as it's been and I'm just as stuck as well lol

Let me know what email you'd like me to send them too, and I'm also just running this in my IDE on my computer so it shouldn't be running through a server or domain.

**Comment by parafoxia** [comment]
Just another weird thing to add to the list lmao.

And ethan.henderson.1998@gmail.com will do fine.

**Comment by Exius999** [comment]
Got it, not a problem. Just sent them over.

**Comment by parafoxia** [comment]
So I've managed to verify there's nothing wrong with the secrets, however I cannot properly test the tokens as the refresh token has expired, meaning analytix is just giving me brand new tokens (which work, making me believe it's something wrong specifically with the tokens you're getting from your account). Can you run the auth flow again so you get new tokens, then send those new tokens to the same email?

**Comment by Exius999** [comment]
Aright, just went ahead and sent it over.

**Comment by parafoxia** [comment]
Okay, so I've managed to work out what's causing the error, I just have no idea why it's happening. The error is being caused by the *dimensions* you're passing through.

For whatever reason, passing certain dimensions on their own raises a 403 error, but not all of them. Out of what I've tested (the below lists are far from exhaustive -- I might come back and complete it), the following raise 403s (but only when passed on their own):

* day
* month
* country
* video

The following work fine on their own:

* insightTrafficSourceType
* liveOrOnDemand
* youtubeProduct
* insightPlaybackLocationType
* operatingSystem
* deviceType
* subscribedStatus
* ageGroup

Weird thing is, combining `day` and `subscribedStatus` actually *does* work. Weirder still, this is only happening with your tokens; I can't replicate the issue with mine. I honestly have no idea what could possible be causing this, but it's worth checking your Google Developers project to make sure everything's okay. Might even be worth just making a new one and seeing if you have any better luck.

**Comment by Exius999** [comment]
Ok, gotcha. Yeah, this is super weird so I'm glad I was able to let you know about this. I appreciate all of the help getting this to work though. I'll go ahead and try this again when I get some more time to work on this.

**Comment by parafoxia** [comment]
Did you manage to make any progress working out why this is happening?

**Comment by parafoxia** [comment]
@Exius999 Hey, been a while! Someone else has had the same issue, and I've come to a new revelation -- I believe the issues you're having are related to revenue data. Something about your channel not being partnered, perhaps.

Can you try something like this?
```py
from analytix.reports.data import ALL_VIDEO_METRICS

METRICS = ALL_VIDEO_METRICS - {
    "estimatedAdRevenue",
    "estimatedRedPartnerRevenue",
    "adImpressions",
    "grossRevenue",
    "estimatedRevenue",
    "monetizedPlaybacks",
    "cpm",
    "playbackBasedCpm",
}
```
Setting your metrics to `METRICS` in the request.

**Comment by Exius999** [comment]
Can definitely tell you I'm not partnered so that would make sense, as for the code there I can give it a shot.

**Comment by parafoxia** [comment]
@ok3721 

Okay, that has to be the issue then. I'll see if I can get a fix out some time this week, though may be this weekend. I have a few ideas of how to do it, though nothing it ideal without introducing breaking changes. Google never makes this stuff easy lmao.

That unclosed client session is coming up cos you're not calling `client.teardown()` -- I might try and wrap that error so that's clearer.

Thanks for the kind words! That exact thing is pretty much exactly why I built this, so I'm glad you're finding it useful (:
